name: Backend Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code to Runner
        uses: actions/checkout@v3
      - name: Login to EC2
        uses: appleboy/ssh-action@v0.1.10
        with: 
          host: ${{secrets.EC2_HOST_BACKEND}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            cd /home/ubuntu/Aws_FullStack
            git pull origin master
            docker stop backend || true
            docker rm backend || true
            docker rmi backend || true
            docker build -t backend -f backend/Dockerfile backend/
            docker run -d -p 5000:5000 --name backend backend