name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/react-app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code to Runner
        uses: actions/checkout@v3
      - name: Login to EC2
        uses: appleboy/ssh-action@v0.1.10
        with: 
          host: ${{secrets.EC2_HOST_FRONTEND}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            cd /home/ubuntu/FullStack_prac
            git pull origin main
            docker stop frontend || true
            docker rm frontend || true
            docker rmi frontend || true
            docker build -t frontend -f frontend/react-app/dockerfile frontend/react-app/
            docker run -d -p 3000:3000 --name frontend frontend